<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BUAT AKUN</name>
   <tag></tag>
   <elementGuidId>c9f09689-47d0-4e6b-a5ec-15a242e6f39e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.button--primary.button--base.button--block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad5b7085-39db-4752-a0d2-08878a05a0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fb06551-3697-4579-8e40-1395ad398049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary button--base  button--block</value>
      <webElementGuid>52e7250f-83c7-42a5-90fe-e192647e630c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unq</name>
      <type>Main</type>
      <value>button-action-default</value>
      <webElementGuid>b74a364f-6854-4b63-b816-a1f2639536cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BUAT AKUN</value>
      <webElementGuid>299a6b3a-c00f-4378-bba6-40d983b8b942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;w-full max-w-[480px] h-full p-[0px] my-0 mx-auto overflow-x-hidden bg-white&quot;]/section[@class=&quot;flex flex-col justify-between w-full h-full md:h-full&quot;]/div[@class=&quot;relative flex-[2] p-[0] flex flex-col justify-between overflow-auto&quot;]/div[@class=&quot;relative flex flex-col h-screen justify-between&quot;]/div[@class=&quot;bottom-[12px] w-full h-auto z-[4]&quot;]/div[@class=&quot;relative w-full h-full flex flex-col justify-center items-center space-y-3 pt-[24px] px-[24px]&quot;]/div[@class=&quot;w-full space-y-4&quot;]/button[@class=&quot;button button--primary button--base  button--block&quot;]</value>
      <webElementGuid>325a2ab3-116f-4d8e-8563-a0627e2a5f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_KECC REWARDS/iframe</value>
      <webElementGuid>1ade294a-30e5-44a3-b1fe-b9aef0f068b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>280985e9-9bbc-4c97-b783-0eda592fac66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>4c65d328-4da0-4428-a159-c426e7076c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sahabat KECC Rewards'])[1]/following::button[1]</value>
      <webElementGuid>e7bb44ef-ce1e-4dcc-8863-dc6f383016bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::button[1]</value>
      <webElementGuid>8f1b9e2c-2631-48c4-a8e1-7143bb7d5ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BUAT AKUN']/parent::*</value>
      <webElementGuid>022687cd-8141-4f79-8964-bbfe0215e37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5675b05c-e3b8-43ff-86a8-d7679c0a49e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'BUAT AKUN' or . = 'BUAT AKUN')]</value>
      <webElementGuid>5f1fc6d3-bcde-4daa-9df0-02e0c4d5326e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
