<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>b1a4221f-7f81-4e29-ba4d-9b4679f8067d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.text-gray-900.text-3xl.justify-end.w-full.items-center.right-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b095710-c67b-4f56-807b-b491b9babd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex text-gray-900 text-3xl justify-end w-full items-center right-0</value>
      <webElementGuid>1672692c-d7bb-4885-bfa6-c98717dae155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>26caa314-a030-40cd-998a-3bedcc8d3da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;opacity-100 pointer-events-auto grid place-items-end overflow-x-hidden overflow-y-auto fixed inset-0 outline-none focus:outline-none transition-all duration-500&quot;]/div[@class=&quot;flex justify-center transform opacity-100 translate-y-0 w-full m-0 mx-auto max-w-full transition-all duration-500&quot;]/div[@class=&quot;relative border-0 py-0 rounded-b-none shadow-3xl flex flex-col w-full max-w-[480px] bg-white outline-none focus:outline-none h-screen rounded-t-none&quot;]/div[@class=&quot;relative flex-auto px-4 py-4 h-screen&quot;]/div[@class=&quot;relative h-full overflow-auto&quot;]/div[@class=&quot;relative flex items-center mb-3&quot;]/div[@class=&quot;flex text-gray-900 text-3xl justify-end w-full items-center right-0&quot;]</value>
      <webElementGuid>bb1f24c0-bbc9-4ea9-97e8-1c62beae071e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_KECC REWARDS/iframe</value>
      <webElementGuid>b50ec45c-003f-4853-9c70-0afd12402f09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>df9ec754-8da3-48b1-8522-abd4ab06f8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAFTAR'])[1]/following::div[8]</value>
      <webElementGuid>70a73323-38d2-4dd4-a339-1ad0c0ec1aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::div[8]</value>
      <webElementGuid>2613725b-853d-44e5-b5d6-d79273ea0a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat &amp; Ketentuan'])[2]/preceding::div[1]</value>
      <webElementGuid>79557865-bd09-4637-888f-c5ca83625c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYARAT DAN KETENTUAN UMUM SAHABAT KECC REWARDS'])[1]/preceding::div[2]</value>
      <webElementGuid>50008b5b-3884-4183-a0a8-4954a3933fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>b2289e8b-f879-4740-8015-a4c5490e17d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>699ddfcb-4163-4d20-bbc2-2b25ca62379c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×' or . = '×')]</value>
      <webElementGuid>19efeca4-b3a5-432a-950c-96d5d32e571d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
