<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>ad706f95-abca-48ea-971c-5400e650f415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-3xl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8ea902b-4d54-441d-9bfc-c9500fb16e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-3xl</value>
      <webElementGuid>01f93054-45ca-45fb-8de8-a1f635d9ae39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>da1db393-4d6c-4a93-855f-e6d0fe340ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;opacity-100 pointer-events-auto grid place-items-end overflow-x-hidden overflow-y-auto fixed inset-0 outline-none focus:outline-none transition-all duration-500&quot;]/div[@class=&quot;flex justify-center transform opacity-100 translate-y-0 w-full m-0 mx-auto max-w-full transition-all duration-500&quot;]/div[@class=&quot;relative border-0 py-0 rounded-b-none shadow-3xl flex flex-col w-full max-w-[480px] bg-white outline-none focus:outline-none h-screen rounded-t-none&quot;]/div[@class=&quot;relative flex-auto px-4 py-4 h-screen&quot;]/div[@class=&quot;relative h-full overflow-auto&quot;]/div[@class=&quot;relative flex items-center mb-[30px] px-[20px]&quot;]/div[@class=&quot;absolute flex justify-end items-center right-0&quot;]/span[@class=&quot;text-3xl&quot;]</value>
      <webElementGuid>8dca6100-f39d-40ee-8751-5f2810a988b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_KECC REWARDS/iframe</value>
      <webElementGuid>3fa0556b-d894-4b91-ad14-0b446b7dc8d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/div/div/div/span</value>
      <webElementGuid>d8a60948-0682-400b-a84d-bbdb1deb0875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[2]/following::span[1]</value>
      <webElementGuid>7561d471-2e96-493e-9b7b-0747244ed004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAFTAR'])[1]/following::span[1]</value>
      <webElementGuid>f5fe3a2f-2341-4c8a-b834-5f35ce579520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adanya Kebijakan Privasi ini adalah komitmen nyata'])[1]/preceding::span[1]</value>
      <webElementGuid>b6579e80-6b71-49df-b7fd-d52ca94386ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>acf9d597-8d36-453c-ba47-703c9ccc707d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span</value>
      <webElementGuid>50276353-6d4f-4c4a-94e4-4ac6498ee4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>e4be6ccd-59df-4410-8f5b-7782a0c568a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
