<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reload Captcha_Captcha</name>
   <tag></tag>
   <elementGuidId>9507c8ee-bf6e-48c5-9329-48673561fa38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Captcha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Captcha&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41c66bee-8345-407f-bd43-88c76745b635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0665802-72eb-45a4-a432-ad49b3461eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Captcha</value>
      <webElementGuid>d14ed62a-490e-4b9d-a818-e9da559d513f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e6b51f8c-d075-42a5-a4c8-5a606ac42193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unq</name>
      <type>Main</type>
      <value>login-input-captcha</value>
      <webElementGuid>087d9306-330f-4997-8dab-d4fbadf34e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>65650aa9-95ad-4a96-b633-d16bb2c3d53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;w-full max-w-[480px] h-full p-[0px] my-0 mx-auto overflow-x-hidden bg-white&quot;]/section[@class=&quot;flex flex-col justify-between w-full h-full md:h-full&quot;]/div[@class=&quot;relative flex-[2] px-[24px] flex flex-col justify-between overflow-auto&quot;]/form[@class=&quot;relative w-full h-full&quot;]/div[@class=&quot;flex flex-col h-full justify-between space-y-4&quot;]/div[@class=&quot;pb-[24px] space-y-4&quot;]/div[@class=&quot;input--captcha space-y-4&quot;]/div[2]/div[@class=&quot;form--input&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>6fdc5be8-aac6-4f95-a757-339eaf226701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Captcha']</value>
      <webElementGuid>4498016b-308f-4af1-8f58-f8024b1a1203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/form/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>e38587c0-37e0-4863-8677-1e359955780c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b8229aca-d94a-4cfc-9e56-b5878d6b4130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Captcha' and @type = 'tel']</value>
      <webElementGuid>803e2a02-c611-4eef-922f-114df6fd21e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
