<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_1.000</name>
   <tag></tag>
   <elementGuidId>7e9d0aac-3d3b-44ec-ac59-8d58513e15aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div/div/section/div/section/div/div[2]/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>97cedc65-c987-4b48-8eef-2c7e89a823ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold leading-[22px]</value>
      <webElementGuid>909d25bd-d013-4b68-b017-0f8d385dbcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.000</value>
      <webElementGuid>7c41e0ab-4b7d-4518-a562-6252c68929c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;w-full max-w-[480px] h-full p-[0px] my-0 mx-auto overflow-x-hidden bg-white&quot;]/section[@class=&quot;flex flex-col justify-between w-full h-full md:h-full&quot;]/div[@class=&quot;relative flex-[2] p-[0]&quot;]/div[@class=&quot;relative px-[24px] pb-[16px] mb-[60px] bg--primary-200&quot;]/section[1]/div[@class=&quot;w-full -mb-[50px] space-y-4 rounded-md shadow-base px-[16px] py-[12px] bg-white space-x-3&quot;]/section[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;w-full flex items-center justify-center space-x-3&quot;]/div[2]/p[@class=&quot;font-semibold leading-[22px]&quot;]</value>
      <webElementGuid>8afaf5a6-f3fe-4338-9a94-b9663f9b0bb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/div/section/div/section/div/div[2]/p[2]</value>
      <webElementGuid>4828358d-d0ed-4df6-8775-f141cbdc013e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yuk diisi!'])[1]/preceding::p[4]</value>
      <webElementGuid>f7077f12-4988-4319-be0a-1c49dc76b4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info'])[1]/preceding::p[5]</value>
      <webElementGuid>05820006-ed69-41a5-80be-9c6325932fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1.000']/parent::*</value>
      <webElementGuid>ad26a681-fe21-42e0-bb86-3b40f53c0236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>a42eb7ca-588a-4fb4-8068-6358dd2e1736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '1.000' or . = '1.000')]</value>
      <webElementGuid>c8b9322d-101f-429c-b279-6be15a5ce788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
