<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Kondisi AndaPersiapan HamilHam_f88055</name>
   <tag></tag>
   <elementGuidId>fa30939b-7db3-431b-9bf4-fe4f1a962d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='ConditionCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;ConditionCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>39df70e7-188c-492f-86ad-cdcc7cf31f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2c3ed7f-6eb9-4307-b5bb-e1a673d5247e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConditionCode</value>
      <webElementGuid>32416987-2192-4e6e-90df-b3295bc2f767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kondisi Anda</value>
      <webElementGuid>cf0d1b7a-90ba-46c5-ab42-da9fcafb7252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Kondisi saat ini</value>
      <webElementGuid>cfa40b90-188e-486b-8d39-91ee9cfc40c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unq</name>
      <type>Main</type>
      <value>register-input-current-condition</value>
      <webElementGuid>b1e0ac14-59a4-4472-befe-ac0a056e91a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>options</name>
      <type>Main</type>
      <value>[object Object],[object Object],[object Object]</value>
      <webElementGuid>3b89c31b-aaac-4f8a-bafa-2581dc4ca6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Kondisi AndaPersiapan HamilHamilMenyusui</value>
      <webElementGuid>d610a099-95c4-4d5b-a0d0-3b13bb4c8db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;w-full max-w-[480px] h-full p-[0px] my-0 mx-auto overflow-x-hidden bg-white&quot;]/section[@class=&quot;flex flex-col justify-between w-full h-full md:h-full&quot;]/div[@class=&quot;relative flex-[2] px-[24px] pb-[24px]&quot;]/section[@class=&quot;space-y-2 h-[80%]&quot;]/form[@class=&quot;space-y-4 flex flex-col h-full justify-between&quot;]/div[@class=&quot;space-y-4 h-full&quot;]/div[@class=&quot;flex flex-col justify-between space-y-4&quot;]/div[1]/div[@class=&quot;space-y-4&quot;]/div[1]/div[@class=&quot;form--input form-input--label&quot;]/select[@class=&quot;input&quot;]</value>
      <webElementGuid>8b6f056c-a55c-4922-bfdc-46fdba4ed714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='ConditionCode']</value>
      <webElementGuid>048224a6-242f-4a89-8acc-26ea7923b158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/section/form/div/div[3]/div/div/div/div/select</value>
      <webElementGuid>40d9ae15-cd4d-4d7b-9f51-840f2d4803dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi saat ini'])[1]/following::select[1]</value>
      <webElementGuid>8522987f-2106-4093-b79b-d693d65511cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Lahir'])[1]/following::select[1]</value>
      <webElementGuid>91936e77-e9e8-43a4-834f-275fb5cdc7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMPAN'])[1]/preceding::select[1]</value>
      <webElementGuid>1369c653-45b0-442f-acef-5fd36f74c3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1f55e3b1-d498-416e-bcb0-102c63b4b058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ConditionCode' and @placeholder = 'Pilih Kondisi Anda' and (text() = 'Pilih Kondisi AndaPersiapan HamilHamilMenyusui' or . = 'Pilih Kondisi AndaPersiapan HamilHamilMenyusui')]</value>
      <webElementGuid>cb46c257-0491-400d-9367-dc74c2b621f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
